Repository deeppavlov/chatsky, pull requests merged in 2023-11, with the labels that each got.

#270 Add docker volumes
  docker-compose.yml
Labels: enhancement

#272 Fix stat tests
  tests/stats/test_defaults.py
  tests/stats/test_tutorials.py
Labels: bug

#206 fix custom messenger interface
  dff/messengers/common/interface.py
  dff/messengers/telegram/interface.py
  tests/pipeline/test_tutorials.py
  tutorials/messengers/web_api_interface/1_fastapi.py
  tutorials/messengers/web_api_interface/2_websocket_chat.py
  tutorials/pipeline/6_custom_messenger_interface.py
  tutorials/pipeline/6_extra_handlers_basic.py
  tutorials/pipeline/6_extra_handlers_full.py
  tutorials/pipeline/7_extra_handlers_and_extensions.py
  tutorials/stats/2_pipeline_integration.py
Labels: documentation

#279 Healthchecks provided for all context storages
  CONTRIBUTING.md
  compose.yml
  docs/source/user_guides/context_guide.rst
  docs/source/user_guides/superset_guide.rst
  makefile
Labels: enhancement
