Repository deeppavlov/chatsky, pull requests merged in 2023-10, with the labels that each got.

#239 fix casting Message to TelegramMessage
  dff/messengers/telegram/messenger.py
Labels: bug

#205 draw.io build make target added
  .dockerignore
  .gitattributes
  .gitignore
  dff/pipeline/pipeline/actor.py
  docs/source/drawio_src/dfe/user_actor.drawio
  makefile
Labels: documentation

#136 Documentation links in tutorials
  docs/source/conf.py
  docs/source/utils/notebook.py
  tests/tutorials/test_format.py
  tutorials/context_storages/1_basics.py
  tutorials/context_storages/2_postgresql.py
  tutorials/context_storages/3_mongodb.py
  tutorials/context_storages/4_redis.py
  tutorials/context_storages/5_mysql.py
  tutorials/context_storages/6_sqlite.py
  tutorials/context_storages/7_yandex_database.py
  tutorials/context_storages/8_db_benchmarking.py
  tutorials/messengers/telegram/1_basic.py
  tutorials/messengers/telegram/2_buttons.py
  tutorials/messengers/telegram/3_buttons_with_callback.py
  tutorials/messengers/telegram/4_conditions.py
  tutorials/messengers/telegram/5_conditions_with_media.py
  tutorials/messengers/telegram/6_conditions_extras.py
  tutorials/messengers/telegram/7_polling_setup.py
  tutorials/messengers/telegram/8_webhook_setup.py
  tutorials/messengers/web_api_interface/1_fastapi.py
  tutorials/messengers/web_api_interface/2_websocket_chat.py
  tutorials/pipeline/1_basics.py
  tutorials/pipeline/2_pre_and_post_processors.py
  tutorials/pipeline/3_pipeline_dict_with_services_basic.py
  tutorials/pipeline/3_pipeline_dict_with_services_full.py
  tutorials/pipeline/4_groups_and_conditions_basic.py
  tutorials/pipeline/4_groups_and_conditions_full.py
  tutorials/pipeline/5_asynchronous_groups_and_services_basic.py
  tutorials/pipeline/5_asynchronous_groups_and_services_full.py
  tutorials/pipeline/6_custom_messenger_interface.py
  tutorials/pipeline/7_extra_handlers_basic.py
  tutorials/pipeline/7_extra_handlers_full.py
  tutorials/pipeline/8_extra_handlers_and_extensions.py
  tutorials/script/core/1_basics.py
  tutorials/script/core/2_conditions.py
  tutorials/script/core/3_responses.py
  tutorials/script/core/4_transitions.py
  tutorials/script/core/5_global_transitions.py
  tutorials/script/core/7_pre_response_processing.py
  tutorials/script/core/8_misc.py
  tutorials/script/core/9_pre_transitions_processing.py
  tutorials/script/responses/1_basics.py
  tutorials/script/responses/2_buttons.py
  tutorials/script/responses/3_media.py
  tutorials/script/responses/4_multi_message.py
  tutorials/utils/1_cache.py
  tutorials/utils/2_lru_cache.py
Labels: documentation

#245 Doclinks added to contribution guide
  CONTRIBUTING.md
Labels: documentation

#249 Add member-order and exclude-members to autodoc config
  docs/source/conf.py
Labels: documentation

#250 Fix basic/full tutorial order
  docs/source/utils/generate_tutorials.py
Labels: bug, documentation

#246 Add docker profiles
  .github/workflows/build_and_publish_docs.yml
  .github/workflows/test_coverage.yml
  .github/workflows/test_full.yml
  CONTRIBUTING.md
  docker-compose.yml
  docs/source/user_guides/superset_guide.rst
  makefile
Labels: enhancement

#209 Feat/update guide
  docs/source/user_guides.rst
  docs/source/user_guides/basic_conceptions.rst
Labels: documentation

#258 Update PR template & remove PR body check
  .github/PULL_REQUEST_TEMPLATE.md
  .github/process_github_events.py
  .github/workflows/event_handler.yml
Labels: workflows
