Repository deeppavlov/chatsky, pull requests merged in 2023-07, with the labels that each got.

#158 Fix streamlit demo image
  img/streamlit.gif
  tutorials/messengers/web_api_interface/4_streamlit_chat.py
Labels: documentation

#155 Fix requirement versions for 3.8
  setup.py
Labels: bug, dependencies

#171 Python version changed
  .github/workflows/test_full.yml
  README.md
  docs/source/get_started.rst
  setup.py
Labels: enhancement

#180 Remove addition of label during context init
  dff/pipeline/pipeline/actor.py
Labels: bug

#179 Remove args, kwargs from condition and label handler factories
  dff/script/conditions/std_conditions.py
  dff/script/labels/std_labels.py
Labels: bug

#181 Remove unused code
  dff/messengers/telegram/utils.py
Labels: refactor/style

#176 Update std_labels.py
  dff/script/labels/std_labels.py
  tests/script/labels/test_labels.py
Labels: bug
