Repository deeppavlov/chatsky, pull requests merged in 2023-02, with the labels that each got.

#77 fix cells order of basic example
  examples/script/core/1_basics.py
Labels: documentation

#76 feat/conditions_without_deep_copied_ctx_and_actor: add new condition …
  dff/script/core/actor.py
Labels: enhancement

#80 cancel workflows in progress
  .github/workflows/build_and_publish_docs.yml
  .github/workflows/codestyle.yml
  .github/workflows/test_coverage.yml
  .github/workflows/test_full.yml
Labels: enhancement

#65 new version of GH pages used
  .github/workflows/build_and_publish_docs.yml
Labels: enhancement

#66 Errorous output removed
  examples/script/responses/1_basics.py
  examples/script/responses/2_buttons.py
  examples/script/responses/3_media.py
  makefile
Labels: bug

#70 new `pydata` theme proposed instead of dff sphinx theme
  docs/source/about_us.rst
  docs/source/community.rst
  docs/source/conf.py
  docs/source/development.rst
  docs/source/documentation.rst
  docs/source/examples.rst
  docs/source/get_started.rst
  docs/source/index.rst
  docs/source/tutorials.rst
  setup.py
Labels: documentation

#63 Docs/contributing and readme update
  CONTRIBUTING.md
  README.md
Labels: documentation, help wanted

#69 Docs/update
  README.md
  dff/context_storages/database.py
  dff/context_storages/json.py
  dff/context_storages/mongo.py
  dff/context_storages/pickle.py
  dff/context_storages/protocol.py
  dff/context_storages/redis.py
  dff/context_storages/shelve.py
  dff/context_storages/sql.py
  dff/context_storages/ydb.py
  dff/messengers/common/interface.py
  dff/messengers/common/types.py
  dff/pipeline/conditions.py
  dff/pipeline/pipeline/component.py
  dff/pipeline/pipeline/pipeline.py
  dff/pipeline/pipeline/utils.py
  dff/pipeline/service/extra.py
  dff/pipeline/service/group.py
  dff/pipeline/service/service.py
  dff/pipeline/service/utils.py
  dff/pipeline/types.py
  dff/script/conditions/std_conditions.py
  dff/script/core/actor.py
  dff/script/core/context.py
  dff/script/core/keywords.py
  dff/script/core/message.py
  dff/script/core/normalization.py
  dff/script/core/script.py
  dff/script/core/types.py
  dff/script/labels/std_labels.py
  dff/script/responses/std_responses.py
  dff/utils/testing/response_comparers.py
  docs/source/about_us.rst
  docs/source/conf.py
  docs/source/documentation.rst
  docs/source/get_started.rst
  docs/source/index.rst
Labels: documentation

#13 Merge telegram into main repository
  .github/workflows/test_coverage.yml
  dff/messengers/common/interface.py
  dff/messengers/telegram/__init__.py
  dff/messengers/telegram/interface.py
  dff/messengers/telegram/message.py
  dff/messengers/telegram/messenger.py
  dff/messengers/telegram/utils.py
  dff/script/core/message.py
  dff/utils/testing/__init__.py
  dff/utils/testing/common.py
  dff/utils/testing/telegram.py
  examples/messengers/telegram/10_no_pipeline_advanced.py
  examples/messengers/telegram/1_basic.py
  examples/messengers/telegram/2_buttons.py
  examples/messengers/telegram/3_buttons_with_callback.py
  examples/messengers/telegram/4_conditions.py
  examples/messengers/telegram/5_conditions_with_media.py
  examples/messengers/telegram/6_conditions_extras.py
  examples/messengers/telegram/7_polling_setup.py
  examples/messengers/telegram/8_webhook_setup.py
  examples/messengers/telegram/9_no_pipeline.py
  setup.py
  tests/examples/test_format.py
  tests/examples/test_utils.py
  tests/messengers/telegram/__init__.py
  tests/messengers/telegram/conftest.py
  tests/messengers/telegram/test_examples.py
  tests/messengers/telegram/test_types.py
  tests/script/core/test_message.py
Labels: enhancement, help wanted

#79 Examples sorting order fixed, theming scripts added to repository
  .github/workflows/build_and_publish_docs.yml
  dff/context_storages/database.py
  dff/context_storages/json.py
  dff/context_storages/mongo.py
  dff/context_storages/pickle.py
  dff/context_storages/shelve.py
  dff/context_storages/sql.py
  dff/context_storages/ydb.py
  dff/messengers/common/interface.py
  docs/source/_static/css/custom.css
  docs/source/_static/images/logo-colab.svg
  docs/source/_static/images/logo-deeppavlov.svg
  docs/source/_static/images/logo-dff.svg
  docs/source/_static/images/logo-download.svg
  docs/source/_static/images/logo-github.svg
  docs/source/_templates/colab-links.html
  docs/source/conf.py
  docs/source/development.rst
  docs/source/tutorials.rst
  docs/source/utils/custom_directives.py
  docs/source/utils/generate_notebook_links.py
  docs/source/utils/regenerate_apiref.py
  makefile
  setup.py
Labels: documentation

#86 revert sphinxcontrib version bump
  setup.py
Labels: bug

#88 docs: remove university
  docs/source/about_us.rst
Labels: documentation

#89 fix: typos
  dff/messengers/common/interface.py
  dff/pipeline/service/extra.py
  dff/script/core/actor.py
  dff/script/core/context.py
  dff/script/core/normalization.py
  docs/source/about_us.rst
  docs/source/conf.py
  docs/source/utils/regenerate_apiref.py
  examples/script/core/1_basics.py
  examples/script/core/2_conditions.py
  examples/script/core/3_responses.py
  examples/script/core/4_transitions.py
  examples/script/core/5_global_transitions.py
  examples/script/core/6_context_serialization.py
  examples/script/core/7_pre_response_processing.py
  examples/script/core/8_misc.py
  examples/script/core/9_pre_transitions_processing.py
  examples/script/responses/4_multi_message.py
  tests/script/core/test_actor.py
  tests/script/core/test_script.py
Labels: documentation

#87 Button 'view on github' added everywhere
  docs/source/_templates/example-links.html
  docs/source/_templates/source-links.html
  docs/source/conf.py
  docs/source/utils/regenerate_apiref.py
Labels: documentation
