Repository deeppavlov/chatsky, pull requests merged in 2023-08, with the labels that each got.

#185 Remove release notes
  .github/workflows/build_and_publish_docs.yml
  docs/source/conf.py
  docs/source/development.rst
  docs/source/utils/pull_release_notes.py
Labels: documentation

#168 pydantic2.0
  dff/context_storages/json.py
  dff/context_storages/mongo.py
  dff/context_storages/redis.py
  dff/context_storages/sql.py
  dff/context_storages/ydb.py
  dff/messengers/telegram/message.py
  dff/script/__init__.py
  dff/script/conditions/std_conditions.py
  dff/script/core/context.py
  dff/script/core/message.py
  dff/script/core/normalization.py
  dff/script/core/script.py
  dff/utils/testing/telegram.py
  setup.py
  tests/context_storages/test_dbs.py
  tests/script/core/test_context.py
  tests/script/core/test_normalization.py
  tutorials/messengers/web_api_interface/3_load_testing_with_locust.py
  tutorials/messengers/web_api_interface/4_streamlit_chat.py
  tutorials/pipeline/4_groups_and_conditions_full.py
  tutorials/script/core/6_context_serialization.py
Labels: dependencies

#187 User guides hidden toctree added
  docs/source/user_guides.rst
  docs/source/user_guides/basic_conceptions.rst
Labels: documentation

#192 Fail tests on skip
  .github/workflows/test_coverage.yml
  .github/workflows/test_full.yml
  makefile
  pytest.ini
  tests/conftest.py
  tests/context_storages/test_dbs.py
  tests/messengers/telegram/test_tutorials.py
  tests/messengers/telegram/test_types.py
Labels: workflows

#194 Normalization functions removed
  dff/script/__init__.py
  tests/script/core/test_normalization.py
Labels: enhancement

#195 Tutorial directives
  .github/workflows/test_coverage.yml
  .github/workflows/test_full.yml
  docs/source/conf.py
  docs/source/utils/notebook.py
  pytest.ini
  setup.py
  tests/pipeline/test_tutorials.py
  tests/tutorials/test_tutorials.py
  tutorials/context_storages/1_basics.py
  tutorials/context_storages/2_postgresql.py
  tutorials/context_storages/3_mongodb.py
  tutorials/context_storages/4_redis.py
  tutorials/context_storages/5_mysql.py
  tutorials/context_storages/6_sqlite.py
  tutorials/context_storages/7_yandex_database.py
  tutorials/messengers/telegram/1_basic.py
  tutorials/messengers/telegram/2_buttons.py
  tutorials/messengers/telegram/3_buttons_with_callback.py
  tutorials/messengers/telegram/4_conditions.py
  tutorials/messengers/telegram/5_conditions_with_media.py
  tutorials/messengers/telegram/6_conditions_extras.py
  tutorials/messengers/telegram/7_polling_setup.py
  tutorials/messengers/telegram/8_webhook_setup.py
  tutorials/messengers/web_api_interface/1_fastapi.py
  tutorials/messengers/web_api_interface/2_websocket_chat.py
  tutorials/messengers/web_api_interface/3_load_testing_with_locust.py
  tutorials/messengers/web_api_interface/4_streamlit_chat.py
  tutorials/pipeline/1_basics.py
  tutorials/pipeline/2_pre_and_post_processors.py
  tutorials/pipeline/3_pipeline_dict_with_services_basic.py
  tutorials/pipeline/3_pipeline_dict_with_services_full.py
  tutorials/pipeline/4_groups_and_conditions_basic.py
  tutorials/pipeline/4_groups_and_conditions_full.py
  tutorials/pipeline/5_asynchronous_groups_and_services_basic.py
  tutorials/pipeline/5_asynchronous_groups_and_services_full.py
  tutorials/pipeline/6_custom_messenger_interface.py
  tutorials/pipeline/7_extra_handlers_basic.py
  tutorials/pipeline/7_extra_handlers_full.py
  tutorials/pipeline/8_extra_handlers_and_extensions.py
  tutorials/script/core/1_basics.py
  tutorials/script/core/2_conditions.py
  tutorials/script/core/3_responses.py
  tutorials/script/core/4_transitions.py
  tutorials/script/core/5_global_transitions.py
  tutorials/script/core/6_context_serialization.py
  tutorials/script/core/7_pre_response_processing.py
  tutorials/script/core/8_misc.py
  tutorials/script/core/9_pre_transitions_processing.py
  tutorials/script/responses/1_basics.py
  tutorials/script/responses/2_buttons.py
  tutorials/script/responses/3_media.py
  tutorials/script/responses/4_multi_message.py
  tutorials/utils/1_cache.py
  tutorials/utils/2_lru_cache.py
Labels: documentation, enhancement

#198 Documentation site **top bar** sections reordered
  docs/source/index.rst
Labels: dependencies

#199 add patch to supress warnings
  docs/source/utils/patching.py
  setup.py
Labels: documentation

#202 Install local dff in tutorial tests
  makefile
  pytest.ini
  tests/tutorials/test_tutorials.py
Labels: bug
