Repository deeppavlov/chatsky, pull requests merged in 2023-03, with the labels that each got.

#85 Add tests without dependency installation
  .github/workflows/test_full.yml
  dff/utils/testing/telegram.py
  tests/messengers/telegram/conftest.py
  tests/messengers/telegram/test_examples.py
  tests/messengers/telegram/test_types.py
Labels: enhancement

#92 Release notes added to docs
  .github/workflows/build_and_publish_docs.yml
  .gitignore
  docs/source/conf.py
  docs/source/development.rst
  docs/source/utils/pull_release_notes.py
  setup.py
Labels: documentation, enhancement

#91 Flattened doc structure and beautiful modules
  CONTRIBUTING.md
  docs/source/conf.py
  docs/source/examples.rst
  docs/source/utils/custom_directives.py
  docs/source/utils/generate_examples.py
  docs/source/utils/generate_notebook_links.py
  docs/source/utils/patching.py
  docs/source/utils/regenerate_apiref.py
  examples/messengers/telegram/10_no_pipeline_advanced.py
  examples/messengers/telegram/1_basic.py
  examples/messengers/telegram/2_buttons.py
  examples/messengers/telegram/3_buttons_with_callback.py
  examples/messengers/telegram/4_conditions.py
  examples/messengers/telegram/5_conditions_with_media.py
  examples/messengers/telegram/6_conditions_extras.py
  examples/messengers/telegram/7_polling_setup.py
  examples/messengers/telegram/8_webhook_setup.py
  examples/messengers/telegram/9_no_pipeline.py
  examples/script/core/1_basics.py
  examples/script/core/2_conditions.py
  examples/script/core/3_responses.py
  examples/script/core/4_transitions.py
  examples/script/core/5_global_transitions.py
  examples/script/core/6_context_serialization.py
  examples/script/core/7_pre_response_processing.py
  examples/script/core/8_misc.py
  examples/script/core/9_pre_transitions_processing.py
  examples/script/responses/1_basics.py
  examples/script/responses/2_buttons.py
  examples/script/responses/3_media.py
  examples/script/responses/4_multi_message.py
  makefile
  tests/examples/test_format.py
Labels: documentation, enhancement

#94 `ydb` dependency lowered
  setup.py
Labels: bug, enhancement

#96 docs: add info about addtitional installations
  README.md
  docs/source/get_started.rst
Labels: documentation
