Repository deeppavlov/chatsky, pull requests merged in 2024-07, with the labels that each got.

#366 Fix stats
  compose.yml
Labels: bug

#328 Telegram interface upgrade
  dff/messengers/common/__init__.py
  dff/messengers/common/interface.py
  dff/messengers/console.py
  dff/messengers/telegram/__init__.py
  dff/messengers/telegram/abstract.py
  dff/messengers/telegram/interface.py
  dff/messengers/telegram/message.py
  dff/messengers/telegram/messenger.py
  dff/messengers/telegram/utils.py
  dff/pipeline/pipeline/pipeline.py
  dff/pipeline/types.py
  dff/script/conditions/__init__.py
  dff/script/conditions/std_conditions.py
  dff/script/core/message.py
  dff/utils/devel/__init__.py
  dff/utils/devel/extra_field_helpers.py
  dff/utils/devel/json_serialization.py
  dff/utils/testing/telegram.py
  docs/source/conf.py
  poetry.lock
  pyproject.toml
  scripts/test.py
  tests/conftest.py
  tests/messengers/telegram/conftest.py
  tests/messengers/telegram/test_happy_paths.json
  tests/messengers/telegram/test_tutorials.py
  tests/messengers/telegram/test_types.py
  tests/messengers/telegram/utils.py
  tests/pipeline/test_messenger_interface.py
  tests/script/conditions/test_conditions.py
  tests/script/core/test_message.py
  tests/utils/test_serialization.py
  tutorials/messengers/telegram/1_basic.py
  tutorials/messengers/telegram/2_attachments.py
  tutorials/messengers/telegram/2_buttons.py
  tutorials/messengers/telegram/3_advanced.py
  tutorials/messengers/telegram/3_buttons_with_callback.py
  tutorials/messengers/telegram/4_conditions.py
  tutorials/messengers/telegram/5_conditions_with_media.py
  tutorials/messengers/telegram/6_conditions_extras.py
  tutorials/messengers/telegram/7_polling_setup.py
  tutorials/messengers/telegram/8_webhook_setup.py
  tutorials/pipeline/2_pre_and_post_processors.py
  tutorials/pipeline/3_pipeline_dict_with_services_full.py
  tutorials/script/responses/2_buttons.py
  tutorials/script/responses/2_media.py
  tutorials/script/responses/3_multi_message.py
  utils/test_data_generators/__init__.py
  utils/test_data_generators/telegram_tutorial_data.py
Labels: enhancement

#36 Merge slots
  compose.yml
  dff/pipeline/pipeline/actor.py
  dff/pipeline/pipeline/pipeline.py
  dff/pipeline/service/extra.py
  dff/pipeline/service/service.py
  dff/pipeline/service/utils.py
  dff/script/core/context.py
  dff/script/core/normalization.py
  dff/slots/__init__.py
  dff/slots/conditions.py
  dff/slots/processing.py
  dff/slots/response.py
  dff/slots/slots.py
  dff/utils/devel/__init__.py
  dff/utils/devel/async_helpers.py
  dff/utils/devel/json_serialization.py
  docs/source/conf.py
  docs/source/user_guides.rst
  docs/source/user_guides/slot_extraction.rst
  poetry.lock
  pyproject.toml
  tests/slots/__init__.py
  tests/slots/conftest.py
  tests/slots/test_slot_manager.py
  tests/slots/test_slot_types.py
  tests/slots/test_tutorials.py
  tests/utils/test_serialization.py
  tutorials/slots/1_basic_example.py
Labels: enhancement

#370 `pepy` badge fix
  .github/process_github_events.py
  README.md
Labels: invalid
